name: CI/CD

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: SSH Remote deploy
      uses: appleboy/ssh-action@master
      with: 
          host: ${{ secrets.TG_HOST }}
          username: ${{ secrets.TG_USER }}
          password: ${{ secrets.TG_PASS }}
          port: ${{ secrets.REMOTE_PORT }}
          script: |
           cd /www/node/node-mysql
           git pull
           export NODE_HOME=/usr/local/lib/nodejs/node-v12.18.1-linux-x64
           export PATH=$PATH:$NODE_HOME/bin
           yarn install
           yarn run build
