name: CI/CD
on:
  push:
    branches: [ master ]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.TG_HOST }}
        username: ${{ secrets.TG_USER }}
        password: ${{ secrets.TG_PASS }}
        # 上面的流程都跟web项目类似，只有下面运行脚本不一致
        script: |
          cd /www/node/node-mysql
          git pull
          export NODE_HOME=/usr/local/lib/nodejs/node-v12.18.1-linux-x64
          export PATH=$PATH:$NODE_HOME/bin
          npm install
          npm run build
​
